### ISSUE TITLE
[Shader Help] Make a vertical version of cinematic

### ISSUE THREAD

**Issue by betterworld-sjq** [Nettakrim/Souper-Secret-Settings#18]
Moving the black bars of up and down side to the left and right side. I've tried to look for the parameters but they're a pain to me, with no coding experience

**Comment by Nettakrim** [comment]
this resourcepack i sent in my discord (which it looks like youre in) should work
[message link](https://discord.com/channels/858269813986164756/1145217791679549460/1267570753201508405) [file link](https://cdn.discordapp.com/attachments/1145217791679549460/1267570752916291637/aspect.zip?ex=6756a201&is=67555081&hm=01dfcf88fce1b987a2e849666c0d70b48ca2b51426fa22ec845f153c4efb344a&)

in the next update for 1.21.3+ it will be possible to change shader parameters ingame

**Comment by betterworld-sjq** [comment]
> this resourcepack i sent in my discord (which it looks like youre in) should work [message link](https://discord.com/channels/858269813986164756/1145217791679549460/1267570753201508405) [file link](https://cdn.discordapp.com/attachments/1145217791679549460/1267570752916291637/aspect.zip?ex=6756a201&is=67555081&hm=01dfcf88fce1b987a2e849666c0d70b48ca2b51426fa22ec845f153c4efb344a&)
> 
> in the next update for 1.21.3+ it will be possible to change shader parameters ingame

Just put it in the game resourcepack folder and it's done? Or it shall come into work with the Expanded Shaders resourcepack loaded?

**Comment by Nettakrim** [comment]
yeah put it in resourcepacks and enable it and expanded shaders

**Comment by Nettakrim** [comment]
then you can enable it with `/soup:stack add aspect4_3` - also that resourcepack is simple enough that you should be able to figure out how to change it to different aspect ratios
