### ISSUE TITLE
Use in command blocks?

### ISSUE THREAD

**Issue by WankyMcSpastic** [Nettakrim/Souper-Secret-Settings#20]
Is there a way to get these effects to run in a command block?
I'm on a singleplayer world.

**Comment by Nettakrim** [comment]
yes! use https://modrinth.com/mod/client-execution alongside soup

**Comment by WankyMcSpastic** [comment]
Thank you!
It was driving me crazy hahah
I appreciate the quick response, have a good Christmas.
