### ISSUE TITLE
using /execute doesnt work for it

### ISSUE THREAD

**Issue by xbox0** [Nettakrim/Souper-Secret-Settings#22]
![image](https://github.com/user-attachments/assets/c347ee4e-16c7-4086-b82e-68c5be86d107)

I need this for a mod im making

also i made drunk shader, so its correct syntax.

**Comment by Nettakrim** [comment]
use
https://modrinth.com/mod/client-execution

**Comment by Nettakrim** [comment]
and yeah that looks right, out of curiousity did you use the guide?
