### ISSUE TITLE
Don't use disable screen mode shaders when drinking soup

### ISSUE THREAD

**Issue by Nettakrim** [Nettakrim/Souper-Secret-Settings#5]

**Comment by MCLegoMan** [comment]
Perspective uses the disable screen mode option to stop shaders from rendering in 'screen' mode, with them instead rendering in 'game' mode.

This option is given to shaders that either could make the ui hard to use or hard to see in 'screen' mode.

If you want to limit shaders from being applied to soup, I'd suggest adding a new option - such as "disable_soup".

**Comment by Nettakrim** [comment]
yeah thats reasonable
